# Generated by Django 3.2 on 2021-04-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210416_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.artist')),
                ('movie_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.movies')),
            ],
            options={
                'unique_together': {('movie_id', 'artist_id')},
            },
        ),
    ]
